### ISSUE TITLE
Where can we find .mexw files?

### ISSUE THREAD

**Issue by universe-2030** [dasproject/das-hand#1]
Hello.

I'm interested in your work "Model-based control of individual finger movements for prosthetic hand function" on TNSRE and followed this link.

However, I cannot find mexw file from github webpage.

Where can we find .mexw files?

Thank you.

Sincerely,

**Comment by dblana** [comment]
Hello, the mexw files are included in the release: https://github.com/dasproject/das-hand/releases/tag/v1.0
